github.com:
    users:
        Angel-CyberTech:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Angel-CyberTech
